python3 upload_video.py --file="testing.mov"
                        --title="Video Automatically uploaded"
                        --description="Testing video for automatic youtube channel"
                        --keywords="AI,Python Automation, Youtube Automation"
                        --category="28"
                        --privacyStatus="private"